In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
plt.style.use('ggplot')
from sympy import *
from matplotlib import cm
from sklearn.datasets import load_boston
from sklearn.cross_validation import KFold
from sklearn.cross_validation import cross_val_score
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
%matplotlib inline
def scan_from_csv(filename):
    return pd.read_csv(filename,na_values='None')

def write_answer_to_file(answer,file):
    with open(file, 'w') as answer_file:  
        answer_file.write(answer)

In [116]:
l1 = np.array([20,30,20,30,20])
l2 = np.array([20,30,50,60,30])
f_air = np.array([75,105,85])
f_wat = np.array([75,55,95])
db = 0.1
dr_air = np.array([2,3,2])*0.1
dr_wat = np.array([7,5,7])*0.1
x1 = 0.5
x2 = 0.2
L = 125
F = 3.6
n = 4/3
lambd = 661*1e-7

In [122]:
def calc(x,L,F,f,dr,n):
    a1 = x/L
    print(a1,a1*((0.05/x)**2 + (1/L)**2)**0.5)
    d = f*F/(f-F)
    s_d = (2*(1/np.mean(f))**2 + 0.05**2)**0.5
    print(d)
    L2 = dr + db
    s_L2 = 0.05/np.mean(L2)
    print(L2)
    G = f/d
    s_G = ((1/np.mean(f))**2 + s_d**2)**0.5
    print(G)
    L1 = L2/G
    s_L1 = (s_L2**2 + s_G**2)**0.5
    print(L1)
    a2 = lambd/L1
    print(a2,a2*(0.05**2 + s_L1**2)**0.5)

In [123]:
calc(x1,L,F,f_air, dr_air,1)

0.004 0.00040127795852750256
[ 3.78151261  3.72781065  3.75921376]
[ 0.3  0.4  0.3]
[ 19.83333333  28.16666667  22.61111111]
[ 0.01512605  0.01420118  0.01326781]
[ 0.00436994  0.00465454  0.00498198] [ 0.00072972  0.00077725  0.00083192]


In [124]:
calc(x2,L,F,f_wat, dr_wat,1)

0.0016 0.0004002047475980264
[ 3.78151261  3.85214008  3.74179431]
[ 0.8  0.6  0.8]
[ 19.83333333  14.27777778  25.38888889]
[ 0.04033613  0.04202335  0.03150985]
[ 0.00163873  0.00157294  0.00209776] [ 0.00016536  0.00015872  0.00021168]


In [133]:
av = 4.3*1e-3
nv = 1
aw = 1.65*1e-3
nw = 4/3
bt = (av*nv - aw*nw)/(nw-nv)
s_bt = ((0.6/4)**2 + (0.3/1.6)**2)**0.5

In [134]:
print(bt*1e3,s_bt*bt*1e3)

6.3000000000000025 1.512738101093511


In [137]:
n1 = (av-aw)/(av/nw - aw/nv)

In [138]:
print(n1)

1.6825396825396826
